#!/bin/bash
echo "🚀 Quick Guide to Push to GitHub"
echo ""
echo "1. Create Personal Access Token:"
echo "   Go to: https://github.com/settings/tokens"
echo "   Click: Generate new token (classic)"
echo "   Check: repo scope"
echo "   Copy the token (ghp_xxxxx...)"
echo ""
echo "2. Update git remote:"
echo "   git remote set-url origin https://YOUR_TOKEN@github.com/mnasarudin/v0-tos.git"
echo ""
echo "3. Push:"
echo "   git add ."
echo "   git commit -m \"Fix Railway deployment\""
echo "   git push origin main"
echo ""
echo "See PUSH_TO_GITHUB.md for detailed steps!"
