#!/bin/bash

echo "🚀 Quick Deployment Guide"
echo ""
echo "The EASIEST way to deploy is Railway:"
echo ""
echo "1. Go to: https://railway.app/new"
echo "2. Click 'Deploy from GitHub repo'"
echo "3. Select your repository"
echo "4. Add environment variables:"
echo "   - NODE_ENV=production"
echo "   - GMAIL_USER=your-email@gmail.com"
echo "   - GMAIL_PASS=your-gmail-app-password"
echo ""
echo "5. Get your HTTPS URL from Railway dashboard"
echo "6. Test camera - it will work! ✅"
echo ""
echo "That's it! Your app will be live with HTTPS in minutes."
echo ""
echo "📖 Full guide: See DEPLOY_TO_RAILWAY.md"
