#!/bin/bash

echo "📱 Twilio SMS Setup for Intern Attendance System"
echo "=================================================="
echo ""
echo "This script will help you set up SMS verification using Twilio."
echo ""
echo "Step 1: Create a free Twilio account"
echo "   👉 Go to: https://www.twilio.com/try-twilio"
echo "   👉 Sign up (it's free to start)"
echo ""
echo "Step 2: Get your credentials"
echo "   👉 After signing up, go to your Dashboard"
echo "   👉 Find your Account SID and Auth Token"
echo ""
echo "Step 3: Buy a phone number"
echo "   👉 Go to Phone Numbers > Buy a number"
echo "   👉 Choose one that can send SMS"
echo "   👉 Note the number (format: +1234567890)"
echo ""
echo "Step 4: Enter your credentials below"
echo "===================================="
echo ""

read -p "Enter your Twilio Account SID: " ACCOUNT_SID
read -p "Enter your Twilio Auth Token: " AUTH_TOKEN
read -p "Enter your Twilio Phone Number (with country code, e.g., +60123456789): " PHONE_NUMBER

# Create .env.local file
cat > .env.local << EOF
# Twilio SMS Configuration
# Auto-generated by setup-twilio.sh

TWILIO_ACCOUNT_SID=$ACCOUNT_SID
TWILIO_AUTH_TOKEN=$AUTH_TOKEN
TWILIO_PHONE_NUMBER=$PHONE_NUMBER
EOF

echo ""
echo "✅ Configuration saved to .env.local"
echo ""
echo "Step 5: Rebuild and restart the application"
echo "=========================================="
echo ""
echo "Run these commands:"
echo "  npm run build"
echo "  npx pm2 restart intern-attendance-system"
echo ""
echo "Or run this script with auto-rebuild:"
echo "  chmod +x setup-twilio.sh && ./setup-twilio.sh"
echo ""

read -p "Do you want to rebuild and restart now? (y/n): " REBUILD
if [ "$REBUILD" = "y" ] || [ "$REBUILD" = "Y" ]; then
    echo "Building application..."
    npm run build
    echo "Restarting application..."
    npx pm2 restart intern-attendance-system
    echo ""
    echo "✅ Application restarted with SMS support!"
    echo ""
    echo "Test your setup:"
    echo "  1. Go to http://localhost:3000/signup"
    echo "  2. Fill out the form"
    echo "  3. Enter your phone number"
    echo "  4. You should receive an SMS with the verification code"
else
    echo "Configuration complete. Remember to rebuild and restart manually."
fi



