/**
 * PDF Export utilities
 * Uses jsPDF to export tables to PDF
 * Client-side only - should only be called from browser
 */

// Dynamic import to avoid SSR issues
const getJsPDF = async () => {
  if (typeof window === 'undefined') {
    throw new Error('PDF export is only available in the browser')
  }
  const { default: jsPDF } = await import('jspdf')
  return jsPDF
}

interface Column {
  header: string
  accessor: string | ((row: any) => string)
  width: number
}

interface ExportTableToPDFOptions {
  title: string
  columns: Column[]
  data: any[]
  filename?: string
  filterText?: string
  userName?: string
  userDepartment?: string
}

export async function exportTableToPDF(options: ExportTableToPDFOptions): Promise<void> {
  const {
    title,
    columns,
    data,
    filename = `export-${new Date().toISOString().split('T')[0]}.pdf`,
    filterText,
    userName,
    userDepartment
  } = options

  // Check if we're in browser
  if (typeof window === 'undefined') {
    console.error('PDF export is only available in the browser')
    return
  }

  // Dynamic import to avoid SSR issues
  const jsPDFModule = await getJsPDF()
  const jsPDF = jsPDFModule.default || jsPDFModule

  // Create new PDF document
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  })

  // Set font
  doc.setFontSize(16)
  doc.text(title, 14, 15)

  // Add filter text if provided
  if (filterText) {
    doc.setFontSize(10)
    doc.text(filterText, 14, 22)
  }

  // Add user info if provided
  let yPos = filterText ? 28 : 22
  if (userName || userDepartment) {
    doc.setFontSize(9)
    if (userName) {
      doc.text(`Generated by: ${userName}`, 14, yPos)
      yPos += 5
    }
    if (userDepartment) {
      doc.text(`Department: ${userDepartment}`, 14, yPos)
      yPos += 5
    }
    yPos += 3
  }

  // Add date
  doc.setFontSize(9)
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, yPos)
  yPos += 8

  // Table settings
  const startX = 14
  const startY = yPos
  const rowHeight = 8
  const pageHeight = doc.internal.pageSize.height
  let currentY = startY

  // Draw table header
  doc.setFontSize(10)
  doc.setFont(undefined, 'bold')
  let xPos = startX
  
  columns.forEach((column) => {
    doc.text(column.header, xPos, currentY)
    xPos += column.width
  })

  currentY += rowHeight
  doc.setLineWidth(0.5)
  doc.line(startX, currentY - 2, startX + columns.reduce((sum, col) => sum + col.width, 0), currentY - 2)

  // Draw table rows
  doc.setFont(undefined, 'normal')
  doc.setFontSize(9)

  data.forEach((row, index) => {
    // Check if we need a new page
    if (currentY + rowHeight > pageHeight - 20) {
      doc.addPage()
      currentY = 20
    }

    xPos = startX
    columns.forEach((column) => {
      let cellValue = ''
      if (typeof column.accessor === 'function') {
        cellValue = column.accessor(row) || '-'
      } else {
        cellValue = row[column.accessor] || '-'
      }

      // Truncate long text
      const maxLength = 40
      if (cellValue.length > maxLength) {
        cellValue = cellValue.substring(0, maxLength) + '...'
      }

      doc.text(cellValue.toString(), xPos, currentY)
      xPos += column.width
    })

    currentY += rowHeight

    // Add line between rows
    if (index < data.length - 1) {
      doc.setLineWidth(0.1)
      doc.line(startX, currentY - 2, startX + columns.reduce((sum, col) => sum + col.width, 0), currentY - 2)
    }
  })

  // Save PDF
  doc.save(filename)
}

